import { type NextPage } from "next";
import Head from "next/head";
import useTetris from "~/hooks/useTetris";

//import { api } from "~/utils/api";

const Home: NextPage = () => {
  //const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { board, getNextPieceTiles, paintPiece } = useTetris();
  return (
    <>
      <Head>
        <title>T3 App Tetris</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="grid grid-cols-4 grid-rows-4">
          {getNextPieceTiles().map((color, i) => <div key={i} className={`border w-10 h-10 rounded ${color}`}></div>)}
        </div>
        <div className="grid grid-cols-10 grid-rows-20">
          {board.map((c, i) => {
            const col = i % 10;
            const row = Math.floor(i / 10);

            const { paint, color } = paintPiece(col, row);

            return <div key={i} className={`border w-10 h-10 rounded ${paint ? color : ''}`}></div>;
          })
          }

        </div>
      </main>
    </>
  );
};

export default Home;


